version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - WEB_APP_URL=http://localhost:3000
      - API_KEY=${API_KEY}
    volumes:
      - ./api:/app
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "pip install psycopg2-binary && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BASE_API_URL=http://localhost:8000/api/v1
      - API_KEY=${API_KEY}
    volumes:
      - ./web:/app
    depends_on:
      - api
    command: npm run dev

volumes:
  postgres_data: